name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'npm'
        - name: Install packages
          run: npm i
        - name: Set Creds
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
        - name: Deploy
          run: npm run deploy
